# configuration file for generator of the experiment
# please for now do not use bash environment variables
# (e.g. $HOME) in this file
#
# NB: it works only on ATOS HPC!
#
# TO CUSTOMIZE THIS FILE, COPY IT AS: config.yml 
# (untracked by .gitignore)
#

# platform of the machine:
platform: "ecmwf-hpc2020-intel+openmpi.yml"

# where do you want to put your job scripts
job_dir: "/home/ecme3497/jobs"

# main folder where the experiment will be run
run_dir: "/ec/res4/scratch/ecme3497/ece4"

# where the ecearth4 code is
ece_dir: "/ec/res4/hpcperm/ecme3497/ec-earth-4-fork"

# where the initial data of ecearth4 are (ensure that cmip6-data is properly loaded)
ini_dir: "/lus/h2resw01/hpcperm/ccpd/ECE4-DATA-EOCENE"

# account for billing
account: "spitnuri"

# schedule settings
schedule:
  start: 19900101
  end: 19910101
  freq: YEARLY # DAILY, MONTHLY, YEARLY
  nlegs: 1 # number of legs

# model resolution
resolution:
  oifs: TL63L31
  nemo: PALEORCA2L31

# slurm launch method
launch-method: "slurm-wrapper-taskset" # slurm-hetjob, slurm-mp-taskset, slurm-shell, slurm-wrapper-taskset

# tuning file
tuning: tuning-TL63ORCA2_v21.yml
