# configuration file for generator of the experiment
# please for now do not use bash environment variables
# (e.g. $HOME) in this file
#
# NB: it works only on ATOS HPC!
#
# TO CUSTOMIZE THIS FILE, COPY IT AS: config.yml 
# (untracked by .gitignore)
#

# platform of the machine:
platform: "ecmwf-hpc2020-intel+openmpi.yml"

# where do you want to put your job scripts
job_dir: "/hpcperm/ecearth4/jobs"

# main folder where the experiment will be run
run_dir: "/scratch/ece4"

# where the ecearth4 code is
ece_dir: "/hpcperm/ecearth4/src"

# where the initial data of ecearth4 are (ensure that cmip6-data is properly loaded)
ini_dir: "/hpcperm/ece-4-database"

# account for billing
account: "hpcaccount"

# schedule settings
schedule:
  start: 19900101
  end: 19910101
  freq: YEARLY # DAILY, MONTHLY, YEARLY
  nlegs: 1 # number of legs

# model resolution
resolution:
  oifs: TL63L31
  nemo: ORCA2L31

# slurm launch method
launch-method: "slurm-wrapper-taskset" # slurm-hetjob, slurm-mp-taskset, slurm-shell, slurm-wrapper-taskset

# tuning file
tuning: tuning-default.yml
